import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1756907488295 implements MigrationInterface {
    name = 'InitialMigration1756907488295'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "permissionId" uuid, CONSTRAINT "PK_01f4295968ba33d73926684264f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "group" character varying, "status" "public"."permissions_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "roleId" uuid, "permissionId" uuid, CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "status" "public"."roles_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "roleId" uuid, CONSTRAINT "PK_8acd5cf26ebd158416f477de799" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."files_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "altText" character varying NOT NULL, "fileName" character varying NOT NULL, "mimeType" character varying NOT NULL, "disk" character varying NOT NULL, "conversionsDisk" character varying NOT NULL, "size" integer NOT NULL, "generatedConversions" json, "status" "public"."files_status_enum" NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_addresses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "address" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "pincode" character varying NOT NULL, "country" character varying NOT NULL, "companyId" uuid, CONSTRAINT "PK_cff628c622ac2c8f5a1927356d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_bank_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bankName" character varying NOT NULL, "accountNumber" character varying NOT NULL, "accountHolderName" character varying NOT NULL, "ifscCode" character varying NOT NULL, "upiName" character varying NOT NULL, "upiAddress" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" uuid, CONSTRAINT "PK_6a40f8fb5886f6345a98ef47157" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "idNumber" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyId" uuid, "frontFileId" uuid, "backFileId" uuid, CONSTRAINT "PK_df54bfe584d2de1b722f3072629" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "address" character varying NOT NULL, "city" character varying NOT NULL, "state" character varying NOT NULL, "pincode" character varying NOT NULL, "country" character varying NOT NULL, "gstName" character varying NOT NULL, "gstNumber" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_f41bd3ea569c8c877b9a9063abb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "idNumber" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "frontFileId" uuid, "backFileId" uuid, CONSTRAINT "PK_cea43819156528b63504c4afd4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."collections_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "collections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "tagLine" character varying, "description" character varying, "seoTitle" character varying, "seoKeywords" character varying, "seoDescription" character varying, "status" "public"."collections_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_ed225078e8bf65b448b69105b45" UNIQUE ("name"), CONSTRAINT "UQ_99d0d14f9f23b45d2c6648c4b57" UNIQUE ("slug"), CONSTRAINT "PK_21c00b1ebbd41ba1354242c5c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."types_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "status" "public"."types_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_fa170fda66d232af69b7f880c9e" UNIQUE ("name"), CONSTRAINT "PK_33b81de5358589c738907c3559b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."amenity_categories_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "amenity_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "status" "public"."amenity_categories_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_3f1421545125197f99c7e213f92" UNIQUE ("name"), CONSTRAINT "PK_2de71e0bec58922dc28e08aaf32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."amenities_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "amenities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "status" "public"."amenities_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, "amenityCategoryId" uuid NOT NULL, CONSTRAINT "UQ_8c5f9c7ff7e2174b53d4be10247" UNIQUE ("name"), CONSTRAINT "PK_c0777308847b3556086f2fb233e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_variants_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "productId" uuid NOT NULL, "name" character varying NOT NULL, "price" numeric(10,2) NOT NULL, "compareAtPrice" numeric(10,2), "currency" character varying NOT NULL DEFAULT 'INR', "totalRooms" integer, "capacity" integer, "dimensions" jsonb, "extraBed" jsonb, "foodOptions" jsonb, "status" "public"."product_variants_status_enum" NOT NULL DEFAULT 'active', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1edbb278083e7043c0d178bbcb" ON "product_variants" ("productId", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "tagLine" character varying, "description" text, "address" jsonb, "contact" jsonb, "bookingContact" jsonb, "policies" jsonb, "latitude" numeric(9,6), "longitude" numeric(9,6), "website" character varying, "rating" numeric(10,2), "cancellationPolicy" character varying, "seoTitle" character varying, "seoKeywords" character varying, "seoDescription" character varying, "status" "public"."products_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, "partnerId" uuid NOT NULL, "typeId" uuid, CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_commissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "percentage" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" uuid, "partnerId" uuid, CONSTRAINT "REL_9307481bae8db3361cab0124a8" UNIQUE ("productId"), CONSTRAINT "PK_311d1d651b1ab36b72a9285b93d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "password" character varying, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phone" character varying, "embedMapUrl" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'draft', "isEmailVerified" boolean NOT NULL DEFAULT false, "isPhoneVerified" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP, "passwordResetToken" character varying, "passwordResetExpires" TIMESTAMP, "emailVerificationToken" character varying, "phoneVerificationToken" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_creation_audit" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "targetUserId" uuid NOT NULL, "createdByAdminId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9b626c9be122f1c16f84383bf8a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."blogs_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "blogs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "tagLine" character varying, "description" character varying, "seoTitle" character varying, "seoKeywords" character varying, "seoDescription" character varying, "status" "public"."blogs_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_7b18faaddd461656ff66f32e2d7" UNIQUE ("slug"), CONSTRAINT "PK_e113335f11c926da929a625f118" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pages_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "tagLine" character varying, "description" character varying, "seoTitle" character varying, "seoKeywords" character varying, "seoDescription" character varying, "status" "public"."pages_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_fe66ca6a86dc94233e5d7789535" UNIQUE ("slug"), CONSTRAINT "PK_8f21ed625aa34c8391d636b7d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."banners_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "banners" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "tagLine" character varying, "description" character varying, "status" "public"."banners_status_enum" NOT NULL DEFAULT 'draft', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid, "mobileImageId" uuid, "desktopImageId" uuid, CONSTRAINT "PK_e9b186b959296fcb940790d31c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."testimonials_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "testimonials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "authorName" character varying NOT NULL, "authorDesignation" character varying, "company" character varying, "message" text NOT NULL, "rating" double precision NOT NULL, "source" character varying, "status" "public"."testimonials_status_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "imageId" uuid, "videoId" uuid, "userId" uuid, CONSTRAINT "PK_63b03c608bd258f115a0a4a1060" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "enquiry_replies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "fileId" uuid, "enquiryId" uuid, CONSTRAINT "PK_1ebd9b6721dfd6b235a655032ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."enquiries_status_enum" AS ENUM('new', 'assigned', 'in progress', 'follow up', 'converted', 'rejected', 'closed')`);
        await queryRunner.query(`CREATE TYPE "public"."enquiries_type_enum" AS ENUM('enquiry', 'support')`);
        await queryRunner.query(`CREATE TABLE "enquiries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "subject" character varying, "message" text NOT NULL, "source" character varying, "leadSource" jsonb, "customFields" jsonb, "status" "public"."enquiries_status_enum" NOT NULL DEFAULT 'new', "type" "public"."enquiries_type_enum" NOT NULL DEFAULT 'enquiry', "emailSentAt" TIMESTAMP, "whatsappMessageSentAt" TIMESTAMP, "smsSentAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid, CONSTRAINT "PK_1516c8a887df94dc119a1db749e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_type_enum" AS ENUM('fixed', 'percentage', 'free_shipping', 'buy_x_get_y_free', 'buy_x_get_y_discount')`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_applicableon_enum" AS ENUM('allProducts', 'specificProducts', 'specificCollections')`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_status_enum" AS ENUM('active', 'inactive', 'expired', 'scheduled')`);
        await queryRunner.query(`CREATE TABLE "discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "type" "public"."discounts_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "eligibleProductIds" text, "freeProductIds" text, "buyQuantity" integer, "getQuantity" integer, "minimumOrderValue" numeric(10,2), "maximumDiscountValue" numeric(10,2), "applicableOn" "public"."discounts_applicableon_enum" NOT NULL DEFAULT 'allProducts', "startDate" TIMESTAMP WITH TIME ZONE NOT NULL, "endDate" TIMESTAMP WITH TIME ZONE NOT NULL, "usageLimit" integer NOT NULL DEFAULT '1', "usedCount" integer NOT NULL DEFAULT '0', "status" "public"."discounts_status_enum" NOT NULL DEFAULT 'inactive', "promoCode" character varying NOT NULL, "isPublic" boolean NOT NULL DEFAULT true, "uptoDiscount" boolean NOT NULL DEFAULT false, "isFeatured" boolean NOT NULL DEFAULT false, "isLimitedTime" boolean NOT NULL DEFAULT false, "isExclusive" boolean NOT NULL DEFAULT false, "isFreeShipping" boolean NOT NULL DEFAULT false, "maxApplicationsPerOrder" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid NOT NULL, CONSTRAINT "UQ_21fc8b5cb454c415de5ad14b60e" UNIQUE ("promoCode"), CONSTRAINT "PK_66c522004212dc814d6e2f14ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orderId" uuid NOT NULL, "productId" uuid, "productSnapshot" jsonb, "productVariantId" character varying, "productVariantSnapshot" jsonb, "currency" character varying(3) NOT NULL, "pricePerNight" numeric(10,2) NOT NULL, "numberOfRooms" integer NOT NULL, "nights" integer NOT NULL, "capacity" integer NOT NULL, "cancellationPolicy" text, "specialRequests" text, "extraBed" jsonb, "foodOptions" jsonb, "taxes" jsonb NOT NULL, "discountDetails" jsonb, "commissionPercentage" numeric(5,2), "commissionAmount" numeric(10,2), "subtotal" numeric(10,2) NOT NULL, "taxAmount" numeric(10,2), "discountAmount" numeric(10,2), "total" numeric(10,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "variantId" uuid, CONSTRAINT "PK_3e59f094c2dc3310d585216a813" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'confirmed', 'cancelled', 'completed', 'refunded', 'failed', 'processing', 'on_hold')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNo" character varying NOT NULL, "checkInDate" date NOT NULL, "checkOutDate" date NOT NULL, "guests" jsonb NOT NULL, "notes" text, "additionalDetails" jsonb, "riskDetails" jsonb, "conversionSummary" jsonb, "communicationChannels" text array, "tags" text array, "currency" character varying(3) NOT NULL, "payment" jsonb, "discountDetails" jsonb, "taxes" jsonb NOT NULL, "commissionRates" jsonb NOT NULL, "commissionPercentage" numeric(5,2), "commissionAmount" numeric(10,2), "subtotal" numeric(10,2) NOT NULL, "taxAmount" numeric(10,2), "discountAmount" numeric(10,2), "total" numeric(10,2) NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "guestId" uuid, "userId" uuid, CONSTRAINT "UQ_9db6621577f0ebac1d156badcf4" UNIQUE ("invoiceNo"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "collection_files" ("collection_id" uuid NOT NULL, "file_id" uuid NOT NULL, CONSTRAINT "PK_f309edb48a1878f0a923d37d5c4" PRIMARY KEY ("collection_id", "file_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fffc44b69de10465492190cd58" ON "collection_files" ("collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9dd6a6a8d02f2f192d6fd5c98e" ON "collection_files" ("file_id") `);
        await queryRunner.query(`CREATE TABLE "product_variant_files" ("productVariantId" uuid NOT NULL, "fileId" uuid NOT NULL, CONSTRAINT "PK_18723945427b50ae4d83c6b191e" PRIMARY KEY ("productVariantId", "fileId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e852706715f149205572d111e3" ON "product_variant_files" ("productVariantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f014f92c5c26744376446d8b0d" ON "product_variant_files" ("fileId") `);
        await queryRunner.query(`CREATE TABLE "product_variants_amenities_amenities" ("productVariantsId" uuid NOT NULL, "amenitiesId" uuid NOT NULL, CONSTRAINT "PK_5bf5a526a84c75018e7bbb81f36" PRIMARY KEY ("productVariantsId", "amenitiesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd252121a8ace931d30dd759ef" ON "product_variants_amenities_amenities" ("productVariantsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cea61695276ad190b0ca3d6da5" ON "product_variants_amenities_amenities" ("amenitiesId") `);
        await queryRunner.query(`CREATE TABLE "products_collections_collections" ("productsId" uuid NOT NULL, "collectionsId" uuid NOT NULL, CONSTRAINT "PK_6dd7b2ee99a3c1092845d83964d" PRIMARY KEY ("productsId", "collectionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6808345e877db7b043bbcd1241" ON "products_collections_collections" ("productsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_87986a08ecb8adf47e4f800948" ON "products_collections_collections" ("collectionsId") `);
        await queryRunner.query(`CREATE TABLE "products_amenities_amenities" ("productsId" uuid NOT NULL, "amenitiesId" uuid NOT NULL, CONSTRAINT "PK_8c20d0b0be1844819a4d4bf3588" PRIMARY KEY ("productsId", "amenitiesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d8ce74b533930e1db4008a625" ON "products_amenities_amenities" ("productsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e907299eee21e2c890724c02e4" ON "products_amenities_amenities" ("amenitiesId") `);
        await queryRunner.query(`CREATE TABLE "product_files" ("productId" uuid NOT NULL, "fileId" uuid NOT NULL, CONSTRAINT "PK_55b4a9a2c8ab3f938055dff85f8" PRIMARY KEY ("productId", "fileId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56627602b737452ac8e95a0ac7" ON "product_files" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9737fc770d09bd272eb012f98d" ON "product_files" ("fileId") `);
        await queryRunner.query(`CREATE TABLE "user_files" ("user_id" uuid NOT NULL, "file_id" uuid NOT NULL, CONSTRAINT "PK_ad4acd48a6d48734f375967f2d4" PRIMARY KEY ("user_id", "file_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d2cd7418269ab5f7e29926cb1" ON "user_files" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_441a34c084cf04c28aa9c1aeb0" ON "user_files" ("file_id") `);
        await queryRunner.query(`CREATE TABLE "blog_files" ("blog_id" uuid NOT NULL, "file_id" uuid NOT NULL, CONSTRAINT "PK_fac7d8110933b93faf83e56ef96" PRIMARY KEY ("blog_id", "file_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5a2661110386f1ca62d2c9b49e" ON "blog_files" ("blog_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1aeea1ea0d9cc68a2656c85a1" ON "blog_files" ("file_id") `);
        await queryRunner.query(`CREATE TABLE "page_files" ("pageId" uuid NOT NULL, "fileId" uuid NOT NULL, CONSTRAINT "PK_6177dbf8429c6b229b991f1cf48" PRIMARY KEY ("pageId", "fileId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c7aa49b9b5334a09cbe44b5089" ON "page_files" ("pageId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2c8c273ecb5c6386e7fa70ba2" ON "page_files" ("fileId") `);
        await queryRunner.query(`CREATE TABLE "enquiry_files" ("enquiry_id" uuid NOT NULL, "file_id" uuid NOT NULL, CONSTRAINT "PK_0e3fe88cea662efee1f2e615834" PRIMARY KEY ("enquiry_id", "file_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d62dd129830171ab968b2617d6" ON "enquiry_files" ("enquiry_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_591798fc2749f8f0c9a59f9a57" ON "enquiry_files" ("file_id") `);
        await queryRunner.query(`CREATE TABLE "discount_products" ("discountId" uuid NOT NULL, "productId" uuid NOT NULL, CONSTRAINT "PK_fd4904b4af95bd2a246472f5fa0" PRIMARY KEY ("discountId", "productId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d88fdb97e9312a61dbc5ae76c0" ON "discount_products" ("discountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3655a2bcaed38bc7c4a8b4391f" ON "discount_products" ("productId") `);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_f05ccc7935f14874d7f89ba030f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions" ADD CONSTRAINT "FK_cf38f85e52ee274ba9a01901ed2" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_eab26c6cc4b9cc604099bc32dff" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_c8db5603420d119933bbc5c398c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_7e7425b17f9e707331e9a6c7335" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_addresses" ADD CONSTRAINT "FK_659ce6885b667102a05c0e6dec4" FOREIGN KEY ("companyId") REFERENCES "user_companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_bank_accounts" ADD CONSTRAINT "FK_ea55c51fd4c5b0b300e503d511e" FOREIGN KEY ("companyId") REFERENCES "user_companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_documents" ADD CONSTRAINT "FK_5df6423bde85f3552abe9931acc" FOREIGN KEY ("companyId") REFERENCES "user_companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_documents" ADD CONSTRAINT "FK_ffbd2e6016ac9d474894374d86f" FOREIGN KEY ("frontFileId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_documents" ADD CONSTRAINT "FK_4e9eb3d611f75122276542ea441" FOREIGN KEY ("backFileId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_295e2ec0606b47e50687ff46c34" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_documents" ADD CONSTRAINT "FK_7dc8609606e081e1ae0f0d43b4e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_documents" ADD CONSTRAINT "FK_f48cd2762d6dd4a57be3cf75031" FOREIGN KEY ("frontFileId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_documents" ADD CONSTRAINT "FK_594a509109adb0ad4bfdee491c5" FOREIGN KEY ("backFileId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collections" ADD CONSTRAINT "FK_da613d6625365707f8df0f65d81" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "types" ADD CONSTRAINT "FK_8b6a25c4d64f5709755009cc709" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amenity_categories" ADD CONSTRAINT "FK_d1a1be04f8481ee4dd824e96a3d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amenities" ADD CONSTRAINT "FK_e251d044c4ce3da2b72b9ed988c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "amenities" ADD CONSTRAINT "FK_3658f7a5350b83ed20c01a2b82f" FOREIGN KEY ("amenityCategoryId") REFERENCES "amenity_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_99d90c2a483d79f3b627fb1d5e9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_f09bd638c0f09d502c26f434523" FOREIGN KEY ("partnerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_6129aa5c0f65c073ea2f7452195" FOREIGN KEY ("typeId") REFERENCES "types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_commissions" ADD CONSTRAINT "FK_9307481bae8db3361cab0124a8b" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_commissions" ADD CONSTRAINT "FK_0f0bbb38a38be86e07891f6247e" FOREIGN KEY ("partnerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_creation_audit" ADD CONSTRAINT "FK_2b30a0a5e3420405157434d569e" FOREIGN KEY ("targetUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_creation_audit" ADD CONSTRAINT "FK_c7db1320fca4a1fa59308b83757" FOREIGN KEY ("createdByAdminId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "blogs" ADD CONSTRAINT "FK_50205032574e0b039d655f6cfd3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_9a7bd99d7450d1c6186ef48fd04" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banners" ADD CONSTRAINT "FK_f5e969f34b23458e65a1603187b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banners" ADD CONSTRAINT "FK_5c8d28da2db45326e725013709b" FOREIGN KEY ("mobileImageId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "banners" ADD CONSTRAINT "FK_2ea260800ba2d8bbe169b2a6c4d" FOREIGN KEY ("desktopImageId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "testimonials" ADD CONSTRAINT "FK_f41a4b77d07a498cc165024dc76" FOREIGN KEY ("imageId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "testimonials" ADD CONSTRAINT "FK_dbd1aff99188cf757b6988e9762" FOREIGN KEY ("videoId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "testimonials" ADD CONSTRAINT "FK_e4e5bb62ec2874c440b6cc3362f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enquiry_replies" ADD CONSTRAINT "FK_ad98c1dab109f991c422f700fba" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enquiry_replies" ADD CONSTRAINT "FK_b9beeab77d521ae1e387d4afa72" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enquiry_replies" ADD CONSTRAINT "FK_f8c0863394b33736cd89ed4181f" FOREIGN KEY ("enquiryId") REFERENCES "enquiries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enquiries" ADD CONSTRAINT "FK_75c7ed461ab43658772e0819ebc" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD CONSTRAINT "FK_dce34864ac17183325e5d08ddf0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_28b66449cf7cd76444378ad4e92" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_27ca18f2453639a1cafb7404ece" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_30a06acc0d68f5700280ca3201f" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_3b7c4a35f210006bbd48938f827" FOREIGN KEY ("guestId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_files" ADD CONSTRAINT "FK_fffc44b69de10465492190cd58b" FOREIGN KEY ("collection_id") REFERENCES "collections"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "collection_files" ADD CONSTRAINT "FK_9dd6a6a8d02f2f192d6fd5c98ea" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_variant_files" ADD CONSTRAINT "FK_e852706715f149205572d111e38" FOREIGN KEY ("productVariantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_variant_files" ADD CONSTRAINT "FK_f014f92c5c26744376446d8b0dc" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_variants_amenities_amenities" ADD CONSTRAINT "FK_dd252121a8ace931d30dd759ef8" FOREIGN KEY ("productVariantsId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_variants_amenities_amenities" ADD CONSTRAINT "FK_cea61695276ad190b0ca3d6da50" FOREIGN KEY ("amenitiesId") REFERENCES "amenities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products_collections_collections" ADD CONSTRAINT "FK_6808345e877db7b043bbcd1241c" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_collections_collections" ADD CONSTRAINT "FK_87986a08ecb8adf47e4f8009480" FOREIGN KEY ("collectionsId") REFERENCES "collections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products_amenities_amenities" ADD CONSTRAINT "FK_2d8ce74b533930e1db4008a6250" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_amenities_amenities" ADD CONSTRAINT "FK_e907299eee21e2c890724c02e40" FOREIGN KEY ("amenitiesId") REFERENCES "amenities"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_files" ADD CONSTRAINT "FK_56627602b737452ac8e95a0ac78" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_files" ADD CONSTRAINT "FK_9737fc770d09bd272eb012f98d8" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_files" ADD CONSTRAINT "FK_8d2cd7418269ab5f7e29926cb18" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_files" ADD CONSTRAINT "FK_441a34c084cf04c28aa9c1aeb0b" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "blog_files" ADD CONSTRAINT "FK_5a2661110386f1ca62d2c9b49e8" FOREIGN KEY ("blog_id") REFERENCES "blogs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "blog_files" ADD CONSTRAINT "FK_e1aeea1ea0d9cc68a2656c85a17" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "page_files" ADD CONSTRAINT "FK_c7aa49b9b5334a09cbe44b5089e" FOREIGN KEY ("pageId") REFERENCES "pages"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "page_files" ADD CONSTRAINT "FK_f2c8c273ecb5c6386e7fa70ba2d" FOREIGN KEY ("fileId") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "enquiry_files" ADD CONSTRAINT "FK_d62dd129830171ab968b2617d64" FOREIGN KEY ("enquiry_id") REFERENCES "enquiries"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "enquiry_files" ADD CONSTRAINT "FK_591798fc2749f8f0c9a59f9a579" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_products" ADD CONSTRAINT "FK_d88fdb97e9312a61dbc5ae76c0d" FOREIGN KEY ("discountId") REFERENCES "discounts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "discount_products" ADD CONSTRAINT "FK_3655a2bcaed38bc7c4a8b4391fb" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "discount_products" DROP CONSTRAINT "FK_3655a2bcaed38bc7c4a8b4391fb"`);
        await queryRunner.query(`ALTER TABLE "discount_products" DROP CONSTRAINT "FK_d88fdb97e9312a61dbc5ae76c0d"`);
        await queryRunner.query(`ALTER TABLE "enquiry_files" DROP CONSTRAINT "FK_591798fc2749f8f0c9a59f9a579"`);
        await queryRunner.query(`ALTER TABLE "enquiry_files" DROP CONSTRAINT "FK_d62dd129830171ab968b2617d64"`);
        await queryRunner.query(`ALTER TABLE "page_files" DROP CONSTRAINT "FK_f2c8c273ecb5c6386e7fa70ba2d"`);
        await queryRunner.query(`ALTER TABLE "page_files" DROP CONSTRAINT "FK_c7aa49b9b5334a09cbe44b5089e"`);
        await queryRunner.query(`ALTER TABLE "blog_files" DROP CONSTRAINT "FK_e1aeea1ea0d9cc68a2656c85a17"`);
        await queryRunner.query(`ALTER TABLE "blog_files" DROP CONSTRAINT "FK_5a2661110386f1ca62d2c9b49e8"`);
        await queryRunner.query(`ALTER TABLE "user_files" DROP CONSTRAINT "FK_441a34c084cf04c28aa9c1aeb0b"`);
        await queryRunner.query(`ALTER TABLE "user_files" DROP CONSTRAINT "FK_8d2cd7418269ab5f7e29926cb18"`);
        await queryRunner.query(`ALTER TABLE "product_files" DROP CONSTRAINT "FK_9737fc770d09bd272eb012f98d8"`);
        await queryRunner.query(`ALTER TABLE "product_files" DROP CONSTRAINT "FK_56627602b737452ac8e95a0ac78"`);
        await queryRunner.query(`ALTER TABLE "products_amenities_amenities" DROP CONSTRAINT "FK_e907299eee21e2c890724c02e40"`);
        await queryRunner.query(`ALTER TABLE "products_amenities_amenities" DROP CONSTRAINT "FK_2d8ce74b533930e1db4008a6250"`);
        await queryRunner.query(`ALTER TABLE "products_collections_collections" DROP CONSTRAINT "FK_87986a08ecb8adf47e4f8009480"`);
        await queryRunner.query(`ALTER TABLE "products_collections_collections" DROP CONSTRAINT "FK_6808345e877db7b043bbcd1241c"`);
        await queryRunner.query(`ALTER TABLE "product_variants_amenities_amenities" DROP CONSTRAINT "FK_cea61695276ad190b0ca3d6da50"`);
        await queryRunner.query(`ALTER TABLE "product_variants_amenities_amenities" DROP CONSTRAINT "FK_dd252121a8ace931d30dd759ef8"`);
        await queryRunner.query(`ALTER TABLE "product_variant_files" DROP CONSTRAINT "FK_f014f92c5c26744376446d8b0dc"`);
        await queryRunner.query(`ALTER TABLE "product_variant_files" DROP CONSTRAINT "FK_e852706715f149205572d111e38"`);
        await queryRunner.query(`ALTER TABLE "collection_files" DROP CONSTRAINT "FK_9dd6a6a8d02f2f192d6fd5c98ea"`);
        await queryRunner.query(`ALTER TABLE "collection_files" DROP CONSTRAINT "FK_fffc44b69de10465492190cd58b"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_3b7c4a35f210006bbd48938f827"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_30a06acc0d68f5700280ca3201f"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_27ca18f2453639a1cafb7404ece"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_28b66449cf7cd76444378ad4e92"`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP CONSTRAINT "FK_dce34864ac17183325e5d08ddf0"`);
        await queryRunner.query(`ALTER TABLE "enquiries" DROP CONSTRAINT "FK_75c7ed461ab43658772e0819ebc"`);
        await queryRunner.query(`ALTER TABLE "enquiry_replies" DROP CONSTRAINT "FK_f8c0863394b33736cd89ed4181f"`);
        await queryRunner.query(`ALTER TABLE "enquiry_replies" DROP CONSTRAINT "FK_b9beeab77d521ae1e387d4afa72"`);
        await queryRunner.query(`ALTER TABLE "enquiry_replies" DROP CONSTRAINT "FK_ad98c1dab109f991c422f700fba"`);
        await queryRunner.query(`ALTER TABLE "testimonials" DROP CONSTRAINT "FK_e4e5bb62ec2874c440b6cc3362f"`);
        await queryRunner.query(`ALTER TABLE "testimonials" DROP CONSTRAINT "FK_dbd1aff99188cf757b6988e9762"`);
        await queryRunner.query(`ALTER TABLE "testimonials" DROP CONSTRAINT "FK_f41a4b77d07a498cc165024dc76"`);
        await queryRunner.query(`ALTER TABLE "banners" DROP CONSTRAINT "FK_2ea260800ba2d8bbe169b2a6c4d"`);
        await queryRunner.query(`ALTER TABLE "banners" DROP CONSTRAINT "FK_5c8d28da2db45326e725013709b"`);
        await queryRunner.query(`ALTER TABLE "banners" DROP CONSTRAINT "FK_f5e969f34b23458e65a1603187b"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP CONSTRAINT "FK_9a7bd99d7450d1c6186ef48fd04"`);
        await queryRunner.query(`ALTER TABLE "blogs" DROP CONSTRAINT "FK_50205032574e0b039d655f6cfd3"`);
        await queryRunner.query(`ALTER TABLE "user_creation_audit" DROP CONSTRAINT "FK_c7db1320fca4a1fa59308b83757"`);
        await queryRunner.query(`ALTER TABLE "user_creation_audit" DROP CONSTRAINT "FK_2b30a0a5e3420405157434d569e"`);
        await queryRunner.query(`ALTER TABLE "product_commissions" DROP CONSTRAINT "FK_0f0bbb38a38be86e07891f6247e"`);
        await queryRunner.query(`ALTER TABLE "product_commissions" DROP CONSTRAINT "FK_9307481bae8db3361cab0124a8b"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_6129aa5c0f65c073ea2f7452195"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_f09bd638c0f09d502c26f434523"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_99d90c2a483d79f3b627fb1d5e9"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "amenities" DROP CONSTRAINT "FK_3658f7a5350b83ed20c01a2b82f"`);
        await queryRunner.query(`ALTER TABLE "amenities" DROP CONSTRAINT "FK_e251d044c4ce3da2b72b9ed988c"`);
        await queryRunner.query(`ALTER TABLE "amenity_categories" DROP CONSTRAINT "FK_d1a1be04f8481ee4dd824e96a3d"`);
        await queryRunner.query(`ALTER TABLE "types" DROP CONSTRAINT "FK_8b6a25c4d64f5709755009cc709"`);
        await queryRunner.query(`ALTER TABLE "collections" DROP CONSTRAINT "FK_da613d6625365707f8df0f65d81"`);
        await queryRunner.query(`ALTER TABLE "user_documents" DROP CONSTRAINT "FK_594a509109adb0ad4bfdee491c5"`);
        await queryRunner.query(`ALTER TABLE "user_documents" DROP CONSTRAINT "FK_f48cd2762d6dd4a57be3cf75031"`);
        await queryRunner.query(`ALTER TABLE "user_documents" DROP CONSTRAINT "FK_7dc8609606e081e1ae0f0d43b4e"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_295e2ec0606b47e50687ff46c34"`);
        await queryRunner.query(`ALTER TABLE "company_documents" DROP CONSTRAINT "FK_4e9eb3d611f75122276542ea441"`);
        await queryRunner.query(`ALTER TABLE "company_documents" DROP CONSTRAINT "FK_ffbd2e6016ac9d474894374d86f"`);
        await queryRunner.query(`ALTER TABLE "company_documents" DROP CONSTRAINT "FK_5df6423bde85f3552abe9931acc"`);
        await queryRunner.query(`ALTER TABLE "company_bank_accounts" DROP CONSTRAINT "FK_ea55c51fd4c5b0b300e503d511e"`);
        await queryRunner.query(`ALTER TABLE "company_addresses" DROP CONSTRAINT "FK_659ce6885b667102a05c0e6dec4"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_7e7425b17f9e707331e9a6c7335"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_c8db5603420d119933bbc5c398c"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_eab26c6cc4b9cc604099bc32dff"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_cf38f85e52ee274ba9a01901ed2"`);
        await queryRunner.query(`ALTER TABLE "user_permissions" DROP CONSTRAINT "FK_f05ccc7935f14874d7f89ba030f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3655a2bcaed38bc7c4a8b4391f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d88fdb97e9312a61dbc5ae76c0"`);
        await queryRunner.query(`DROP TABLE "discount_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_591798fc2749f8f0c9a59f9a57"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d62dd129830171ab968b2617d6"`);
        await queryRunner.query(`DROP TABLE "enquiry_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2c8c273ecb5c6386e7fa70ba2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7aa49b9b5334a09cbe44b5089"`);
        await queryRunner.query(`DROP TABLE "page_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1aeea1ea0d9cc68a2656c85a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5a2661110386f1ca62d2c9b49e"`);
        await queryRunner.query(`DROP TABLE "blog_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_441a34c084cf04c28aa9c1aeb0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d2cd7418269ab5f7e29926cb1"`);
        await queryRunner.query(`DROP TABLE "user_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9737fc770d09bd272eb012f98d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56627602b737452ac8e95a0ac7"`);
        await queryRunner.query(`DROP TABLE "product_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e907299eee21e2c890724c02e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d8ce74b533930e1db4008a625"`);
        await queryRunner.query(`DROP TABLE "products_amenities_amenities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87986a08ecb8adf47e4f800948"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6808345e877db7b043bbcd1241"`);
        await queryRunner.query(`DROP TABLE "products_collections_collections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cea61695276ad190b0ca3d6da5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd252121a8ace931d30dd759ef"`);
        await queryRunner.query(`DROP TABLE "product_variants_amenities_amenities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f014f92c5c26744376446d8b0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e852706715f149205572d111e3"`);
        await queryRunner.query(`DROP TABLE "product_variant_files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dd6a6a8d02f2f192d6fd5c98e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fffc44b69de10465492190cd58"`);
        await queryRunner.query(`DROP TABLE "collection_files"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_products"`);
        await queryRunner.query(`DROP TABLE "discounts"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_applicableon_enum"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_type_enum"`);
        await queryRunner.query(`DROP TABLE "enquiries"`);
        await queryRunner.query(`DROP TYPE "public"."enquiries_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."enquiries_status_enum"`);
        await queryRunner.query(`DROP TABLE "enquiry_replies"`);
        await queryRunner.query(`DROP TABLE "testimonials"`);
        await queryRunner.query(`DROP TYPE "public"."testimonials_status_enum"`);
        await queryRunner.query(`DROP TABLE "banners"`);
        await queryRunner.query(`DROP TYPE "public"."banners_status_enum"`);
        await queryRunner.query(`DROP TABLE "pages"`);
        await queryRunner.query(`DROP TYPE "public"."pages_status_enum"`);
        await queryRunner.query(`DROP TABLE "blogs"`);
        await queryRunner.query(`DROP TYPE "public"."blogs_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_creation_audit"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_commissions"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1edbb278083e7043c0d178bbcb"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TYPE "public"."product_variants_status_enum"`);
        await queryRunner.query(`DROP TABLE "amenities"`);
        await queryRunner.query(`DROP TYPE "public"."amenities_status_enum"`);
        await queryRunner.query(`DROP TABLE "amenity_categories"`);
        await queryRunner.query(`DROP TYPE "public"."amenity_categories_status_enum"`);
        await queryRunner.query(`DROP TABLE "types"`);
        await queryRunner.query(`DROP TYPE "public"."types_status_enum"`);
        await queryRunner.query(`DROP TABLE "collections"`);
        await queryRunner.query(`DROP TYPE "public"."collections_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_documents"`);
        await queryRunner.query(`DROP TABLE "user_companies"`);
        await queryRunner.query(`DROP TABLE "company_documents"`);
        await queryRunner.query(`DROP TABLE "company_bank_accounts"`);
        await queryRunner.query(`DROP TABLE "company_addresses"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_status_enum"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_permissions"`);
    }

}
